# Top 100 SEO Tags in Hashtag Format
tags_hashtag_format = "#SanatanaKatha #BhagavadGita #KrishnaWisdom #SanatanaDharma #Spirituality #HinduPhilosophy #AncientWisdom #DivineKnowledge #GitaTeachings #KarmaYoga #Dharma #Enlightenment #IndianCulture #EternalTruth #SacredScriptures #VedicWisdom #KrishnaConsciousness #Hinduism #SelfRealization #LifeLessons #InnerPeace #GitaQuotes #GodlyWisdom #HinduMythology #SanatanaTruth #Meditation #BhaktiYoga #DivineMessage #ArjunaKrishna #SpiritualGrowth #SoulJourney #VedicTeachings #Upanishads #SacredTexts #KarmaPhilosophy #PathToLiberation #UniversalTruth #SelfDiscovery #WisdomOfTheGods #Mahabharata #KrishnaLeela #HinduGods #EternalDharma #InnerStrength #YogaOfKnowledge #HolyTeachings #Moksha #SelfAwareness #SacredKnowledge #BhagavadGitaWisdom #RighteousPath #LordKrishna #DharmicPath #Mindfulness #HinduTeachings #HigherConsciousness #JaiShriKrishna #BhaktiMovement #KrishnaDevotion #Mahadev #OmNamahShivaya #SacredWritings #EnlightenedMind #MysticalIndia #TimelessWisdom #FaithInGod #KrishnaWords #BhagavadGitaTeachings #VedicKnowledge #ShriKrishna #HinduCulture #HinduTradition #SpiritualJourney #DivinePath #GodsWisdom #KarmaAction #DivinePurpose #KrishnaLessons #CelestialTruth #PhilosophyOfLife #HinduPhilosophyTeachings #SacredSpirituality #KrishnaSpeaks #MindPower #AncientTexts #SoulPurpose #DharmaVsAdharma #GitaExplained #WisdomOfTheAges #KrishnaArjunaDialogues #PathToTruth #KrishnaBhagwan #DivineBlessings #SacredBhagavadGita #LifeTransformation #KarmaTheory #SanatanaDharmaPrinciples #EternalMessage #SacredGuidance #SupremeWisdom #ShriKrishnaGita"

# Top 30 SEO Tags in Comma-Separated Format
tags_comma_format = "Sanatana Katha, Bhagavad Gita, Krishna Wisdom, Sanatana Dharma, Spirituality, Hindu Philosophy, Ancient Wisdom, Divine Knowledge, Gita Teachings, Karma Yoga, Dharma, Enlightenment, Indian Culture, Eternal Truth, Sacred Scriptures, Krishna Consciousness, Self-Realization, Life Lessons, Inner Peace, Gita Quotes, Hindu Mythology, Meditation, Bhakti Yoga, Divine Message, Spiritual Growth, Soul Journey, Path to Liberation, Universal Truth, Krishna Devotion, Mystical India"

# Videos titles
titles = {

    1: 'How Can I Free Myself from Negative Thoughts? | Bhagavad Gita Wisdom',
    2: 'What is the Significance of Devotion in Life? | Krishna’s Teachings',
    3: 'Why Do I Sometimes Feel Lost on My Spiritual Path? | Gita Insights',
    4: 'How Can I Remain Calm in Times of Crisis? | Bhagavad Gita Guidance',
    5: 'What is the Greatest Obstacle to Spiritual Growth? | Krishna’s Truths',
    6: 'How Do I Overcome Laziness and Procrastination? | Bhagavad Gita Lessons',
    7: 'Why is the Company of Good People Important? | Krishna’s Wisdom',
    8: 'What is the Difference Between Knowledge and Realization? | Gita Explained',
    9: 'How Can I Develop Inner Strength? | Bhagavad Gita Teachings',
    10: 'What is the Best Way to Meditate Upon Krishna? | Gita Insights',
    11: 'How Can I Develop Unshakable Confidence? | Bhagavad Gita Wisdom',
    12: 'What is the Real Meaning of Surrender? | Krishna’s Teachings',
    13: 'How Do I Overcome Attachment to Material Success? | Gita Insights', 
    14: 'Why Do Some People Lose Faith in Difficult Times? | Krishna’s Guidance', 
    15: 'How Can I Stay Committed to My Spiritual Practice? | Bhagavad Gita Truths', 
    16: 'What is the Best Way to Silence the Mind? | Krishna’s Teachings', 
    17: 'Why Does Anger Arise and How Can I Control It? | Gita Wisdom', 
    18: 'How Can I Distinguish Between Real Knowledge and Illusion? | Bhagavad Gita Explained', 
    19: 'What is the Role of Gratitude in Life? | Krishna’s Teachings', 
    20: 'How Do I Maintain Patience When Results Take Time? | Gita Insights',
    21: 'How Can I Stay Peaceful in the Face of Criticism? | Bhagavad Gita Wisdom', 
    22: 'What is the Ultimate Goal of Human Life? | Krishna’s Teachings', 
    23: 'How Do I Let Go of Past Mistakes and Guilt? | Gita Insights', 
    24: 'Why Do Some Find Spiritual Wisdom While Others Remain Ignorant? | Bhagavad Gita Explained', 
    25: 'How Can I Develop True Humility? | Krishna’s Teachings', 
    26: 'What is the Best Way to Overcome Greed? | Bhagavad Gita Lessons', 
    27: 'How Do I Find My True Calling in Life? | Krishna’s Guidance', 
    28: 'Why Do I Feel Incomplete Even When I Achieve Success? | Gita Teachings', 
    29: 'How Can I Serve the World Selflessly? | Bhagavad Gita Wisdom', 
    30: 'What is the Relationship Between Devotion and Wisdom? | Krishna’s Insights', 
    31: 'Why Do People Struggle Between Good and Evil? | Bhagavad Gita Wisdom', 
    32: 'What is the True Meaning of Selflessness? | Krishna’s Teachings', 
    33: 'How Can I Develop Unshakable Faith in Krishna? | Gita Insights', 
    34: 'Why Do People Suffer Even When Doing Good? | Bhagavad Gita Truths', 
    35: 'What is the Greatest Form of Devotion? | Krishna’s Guidance', 
    36: 'How Can I Free Myself from Attachments? | Gita Lessons', 
    37: 'Why Do Some Attain Wisdom While Others Remain Ignorant? | Deep Gita Teachings', 
    38: 'How Can I Strengthen My Willpower? | Bhagavad Gita Explained', 
    39: 'What is the True Meaning of Renunciation? | Krishna’s Teachings', 
    40: 'How Can I Balance Material Life and Spiritual Growth? | Gita Wisdom', 
    41: 'What is the Easiest Way to Attain Krishna? | Bhagavad Gita Wisdom', 
    42: 'Why is the Mind So Restless? | Krishna’s Teachings', 
    43: 'What is the Role of Destiny in Our Lives? | Bhagavad Gita Insights', 
    44: 'How Should One Treat Friends and Enemies? | Krishna’s Guidance', 
    45: 'What is the Greatest Form of Sacrifice? | Bhagavad Gita Lessons', 
    46: 'How Can I Find True Happiness? | Krishna’s Teachings', 
    47: 'What is the Importance of Patience in Spiritual Life? | Gita Insights', 
    48: 'How Can I Maintain Focus on My Spiritual Path? | Krishna’s Advice', 
    49: 'What is the Best Way to Overcome Anger? | Bhagavad Gita Teachings', 
    50: 'How Can I See Divinity in All Beings? | Krishna’s Wisdom', 
    51: 'How Can I Develop Unwavering Focus? | Bhagavad Gita Wisdom',
    52: 'What is the Secret to a Meaningful Life? | Krishna’s Teachings', 
    53: 'How Do I Stop Comparing Myself to Others? | Gita Insights', 
    54: 'Why Do I Feel Lost Even When I Have Everything? | Bhagavad Gita Explained', 
    55: 'How Can I Truly Understand the Meaning of Detachment? | Krishna’s Wisdom', 
    56: 'What is the Best Way to Control My Speech? | Bhagavad Gita Teachings', 
    57: 'Why Does Suffering Exist if God is Merciful? | Gita Insights', 
    58: 'How Can I Recognize the Presence of the Divine in Daily Life? | Krishna’s Teachings',
    59: 'What is the Importance of Faith in Overcoming Challenges? | Bhagavad Gita Lessons',
    60: 'How Can I Purify My Thoughts and Actions? | Krishna’s Guidance', 
    61: 'How Can I Stay Motivated in Difficult Times? | Bhagavad Gita Wisdom'
    }